"""niuniudazuozhan

迁移 ID: d1e63f60aede
父迁移: 
创建时间: 2025-07-25 13:57:29.686972

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd1e63f60aede'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niuniudazuozhan_niuniucooldown',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('last_dao_time', sa.DateTime(), nullable=True, comment='最后导操作时间'),
    sa.Column('last_ri_time', sa.DateTime(), nullable=True, comment='最后日群友时间'),
    sa.Column('daily_targeted_count', sa.Integer(), nullable=False, comment='今日被指定次数'),
    sa.Column('last_reset_date', sa.Date(), nullable=True, comment='最后重置日期'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niuniudazuozhan_niuniucooldown')),
    info={'bind_key': 'niuniudazuozhan'}
    )
    with op.batch_alter_table('niuniudazuozhan_niuniucooldown', schema=None) as batch_op:
        batch_op.create_index('uk_cooldown_user_group', ['user_id', 'group_id'], unique=True)

    op.create_table('niuniudazuozhan_niuniuoperation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='操作用户ID'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('target_user_id', sa.String(length=64), nullable=True, comment='目标用户ID（日群友时使用）'),
    sa.Column('operation_type', sa.Enum('DAO', 'RI_QUNYU', name='operationtype'), nullable=False, comment='操作类型'),
    sa.Column('length_change', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='长度变化'),
    sa.Column('target_length_change', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='目标用户长度变化'),
    sa.Column('operation_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niuniudazuozhan_niuniuoperation')),
    info={'bind_key': 'niuniudazuozhan'}
    )
    with op.batch_alter_table('niuniudazuozhan_niuniuoperation', schema=None) as batch_op:
        batch_op.create_index('idx_operation_target_user_time', ['target_user_id', 'operation_time'], unique=False)
        batch_op.create_index('idx_operation_user_group_time', ['user_id', 'group_id', 'operation_time'], unique=False)

    op.create_table('niuniudazuozhan_userniuniudata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='牛牛长度(cm)'),
    sa.Column('total_operations', sa.Integer(), nullable=False, comment='总操作次数'),
    sa.Column('last_operation_time', sa.DateTime(), nullable=True, comment='最后操作时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niuniudazuozhan_userniuniudata')),
    info={'bind_key': 'niuniudazuozhan'}
    )
    with op.batch_alter_table('niuniudazuozhan_userniuniudata', schema=None) as batch_op:
        batch_op.create_index('idx_user_data_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_user_data_last_operation', ['last_operation_time'], unique=False)
        batch_op.create_index('uk_user_data_user_group', ['user_id', 'group_id'], unique=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('niuniudazuozhan_userniuniudata', schema=None) as batch_op:
        batch_op.drop_index('uk_user_data_user_group')
        batch_op.drop_index('idx_user_data_last_operation')
        batch_op.drop_index('idx_user_data_group_id')

    op.drop_table('niuniudazuozhan_userniuniudata')
    with op.batch_alter_table('niuniudazuozhan_niuniuoperation', schema=None) as batch_op:
        batch_op.drop_index('idx_operation_user_group_time')
        batch_op.drop_index('idx_operation_target_user_time')

    op.drop_table('niuniudazuozhan_niuniuoperation')
    with op.batch_alter_table('niuniudazuozhan_niuniucooldown', schema=None) as batch_op:
        batch_op.drop_index('uk_cooldown_user_group')

    op.drop_table('niuniudazuozhan_niuniucooldown')
    # ### end Alembic commands ###
